name: release-main

on:
  release:
    types: [published]
    branches: [master]

jobs:
  build_wheels:
    name: "Build on ${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build wheels on ${{ matrix.os }}
        uses: pypa/cibuildwheel@v3.3.1

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: distribution-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  release:
    name: >-
      Publish Python 🐍 distribution 📦 to PyPI
    needs: [build_wheels]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pupil-labs-uvc
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Download distribution packages
        uses: actions/download-artifact@v4
        with:
          pattern: distribution-*
          path: dist/
          merge-multiple: true
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
